GET {{url}}/api/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{$auth.token("user")}}

> {%
    client.test("Request to send notification", function() {
        client.assert(response.status === 200, "Response status is not 201");
    });
%}

###

GET {{url}}/api/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{$auth.token("m2m")}}

> {%
    client.test("Request to send notification", function() {
        client.assert(response.status === 200, "Response status is not 201");
    });
%}
