GET {{url}}/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{$auth.token("m2m")}}

> {%
    client.test("Request to get users as m2m", function() {
        client.assert(response.status === 200, "Response status is not 201");
    });
%}

###

GET {{url}}/api/users/01jpaxqadk3f8jc3cwyy5ngbw7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{$auth.token("m2m")}}

> {%
    client.test("Request to get user by id as m2m", function() {
        client.assert(response.status === 200, "Response status is not 201");
    });
%}

###

GET {{url}}/api/users/01jpaxqadk3f8jc3cwyy5ngbw7
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{$auth.token("user")}}

> {%
    client.test("Request to get user by id as logged user", function() {
        client.assert(response.status === 200, "Response status is not 201");
    });
%}

###

GET {{url}}/api/users/01jpaxqadk3f8jc3cwyy5ngbw7
Content-Type: application/json
Accept: application/json

> {%
    client.test("Request to get user by id anonymously", function() {
        client.assert(response.status === 401, "Response status is not 401");
    });
%}
