version: 2
updates:

- package-ecosystem: composer
  directory: "laravel-asana"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php
- package-ecosystem: composer
  directory: "laravel-ohdear"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "laravel-sentry-handler"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "laravel-infrastructure"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "laravel-one"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "phpunit-slicer"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php
