version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - "dep:github-actions"

- package-ecosystem: composer
  directory: "lambda-qr"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "laravel-infrastructure"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "laravel-one"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "laravel-sentry-handler"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "laravel-session"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: composer
  directory: "phpunit-slicer"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:php

- package-ecosystem: docker
  directory: "vapor-ci"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:docker

- package-ecosystem: docker
  directory: "vapor-nginx"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:docker

- package-ecosystem: docker
  directory: "vapor-roadrunner"
  schedule:
    interval: monthly
    time: "06:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 3
  target-branch: master
  labels:
    - dependencies
    - dep:docker
