volumes:
  ollama_data:

services:

  #
  # docker-compose build ollama-and-friends
  #
  ollama-and-friends:
    image: abenevaut/ollama-and-friends:latest
    build:
      context: ollama-and-friends
      dockerfile: Dockerfile
    volumes:
      - ollama_data:/root/.ollama
