ARG TYPE=latest
FROM ollama/ollama:latest

LABEL maintainer="Antoine Benevaut <me@abenevaut.dev>"
LABEL org.opencontainers.image.source=https://github.com/abenevaut/dev.abenevaut

RUN ollama pull qwen3:qwen3:0.6b
