name: 'laravel-one'
description: 'Action to generate static web pages'
inputs:
  url:
    description: 'The base URL of the website'
    required: true
  php-version:
    description: 'The PHP version to use'
    required: true
outputs:
  logs:
    description: "laravel-one output"
    value: ${{ steps.laravel-one-generation.outputs.logs }}
runs:
  using: "composite"
  steps:

    - name: Initialize PHP ${{ inputs.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: abenevaut/laravel-one

    - name: Generate static pages
      id: laravel-one-generation
      run: echo "logs=$(echo laravel-one generate $URL)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        URL: ${{ inputs.url }}

#    - name: Configure Composer cache
#      uses: actions/cache@v3
#      with:
#        path: ~/vendor
#        key: ${{ runner.os }}-node-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}
#        restore-keys: |
#          ${{ runner.os }}-node-php_${{ env.php_version }}-
