tap "homebrew/services"

brew "nginx", restart_service: true, link: true
brew "mysql", restart_service: true, link: true
brew "redis", restart_service: true, link: true
brew "dnsmasq", restart_service: true
brew "php@8.1", restart_service: true, link: true, conflicts_with: ["php"]

brew "composer"
