# frozen_string_literal: true

source 'https://rubygems.org'

gem 'docker-api', require: 'docker'
gem 'dotenv'
gem 'json'
gem 'rubocop', require: false
gem 'rubocop-rspec', require: false
gem 'serverspec'
