# frozen_string_literal: true

source 'https://rubygems.org'

gem 'docker-api', require: 'docker'
gem 'dotenv'
gem 'json'
gem 'rubocop', '>= 1.66.0', require: false
gem 'rubocop-rspec', '>= 3.0.0', require: false
gem 'serverspec'
