# frozen_string_literal: true

source 'https://rubygems.org'

gem 'docker-api', require: 'docker'
gem 'dotenv'
gem 'json'
gem 'rubocop', '>= 1.63.0', require: false
gem 'rubocop-rspec', '>= 2.28.0', require: false
gem 'serverspec'
