name: desktop-publish

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: desktop-release-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y%m%d')"

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Log to github registry
        run: docker login ghcr.io --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/abenevaut/desktop
          tags: |
            type=raw,value=${{ steps.date.outputs.date }}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: desktop
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
