name: lambda-qr-release

on:
  push:
    tags:
      - lambda-qr-*

defaults:
  run:
    working-directory: ./lambda-qr

jobs:

  release:
    runs-on: ubuntu-latest
    environment:
      name: lambda-qr
      url: https://github.com/abenevaut/lambda-qr
    concurrency:
      group: lambda-qr-release-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get current release tag
        id: branch-name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/lambda-qr-}" >> $GITHUB_OUTPUT

      - name: Publish to readonly repository abenevaut/lambda-qr
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/lambda-qr.git
          BRANCH: master
          FOLDER: lambda-qr
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LAMBDA_QR }}
          TAG: ${{ steps.branch-name.outputs.SOURCE_TAG }}
