name: laravel-asana-release

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-asana/**'

defaults:
  run:
    working-directory: ./laravel-asana

jobs:

  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/master')
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Publish to repository opensource/laravel-asana
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-asana.git
          BRANCH: master
          FOLDER: laravel-asana
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_ASANA }}
