name: laravel-ohdear-release

on:
  push:
    tags:
      - laravel-ohdear-*

defaults:
  run:
    working-directory: ./laravel-ohdear

jobs:

  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: laravel-ohdear-release
      cancel-in-progress: false
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get current release tag
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/laravel-ohdear-}

      - name: Publish to repository opensource/laravel-ohdear
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-ohdear.git
          BRANCH: master
          FOLDER: laravel-ohdear
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_OHDEAR }}
          TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
