name: laravel-sentry-handler-test

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-sentry-handler/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'laravel-sentry-handler/**'

defaults:
  run:
    working-directory: ./laravel-sentry-handler

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php_version: [ 81, 82, 83 ]
        include:
          - php_version: 81
            record_coverage: false
          - php_version: 82
            record_coverage: false
          - php_version: 83
            record_coverage: true
    concurrency:
      group: laravel-sentry-handler-test-${{ github.workflow }}-${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: true
    container: ghcr.io/abenevaut/vapor-ci:php${{ matrix.php_version }}
    steps:

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: laravel-sentry-handler/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php_version }}-

      - name: Validate Composer.json
        run: composer validate --strict

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist

      - name: Smelly Code Detector
        if: github.event_name == 'pull_request' && matrix.record_coverage
        run: |
          vendor/bin/smelly-code-detector inspect src | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" > tmp.txt
          sed '$d' tmp.txt > tmp2.txt
          sed '$d' tmp2.txt > tmp.txt
          sed '2d' tmp.txt > tmp2.txt
          sed '2d' tmp2.txt > tmp.txt
          sed '2d' tmp.txt > tmp2.txt
          sed 's/+/|/g' tmp2.txt > ../.github/workflows/smelly-code-detector.txt
          rm tmp.txt tmp2.txt

      - uses: actions/upload-artifact@v4
        with:
          name: smelly-code-detector
          path: ${{ github.workspace }}/.github/workflows/smelly-code-detector.txt
          retention-days: 1
          compression-level: 9
          overwrite: true

      - name: Run tests
        run: |
          vendor/bin/composer-unused
          vendor/bin/smelly-code-detector inspect ./src
          vendor/bin/phparkitect check --config arkitect.php --target-php-version ${{ matrix.original_php_version }}
          vendor/bin/phpcs --standard=PSR12 src tests
          vendor/bin/phpunit

      - name: Send coverage
        if: ${{ matrix.record_coverage }}
        run: codecov -f coverage/clover.xml -F laravel-sentry-handler
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  comment:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pull-requests: write # needed by `NejcZdovc/comment-pr` action
    strategy:
      fail-fast: true
      matrix:
        php_version: [ 81, 82, 83 ]
        include:
          - php_version: 81
            record_coverage: false
          - php_version: 82
            record_coverage: false
          - php_version: 83
            record_coverage: true
    concurrency:
      group: laravel-sentry-handler-comment-${{ github.workflow }}-${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: false
    steps:

      - uses: actions/download-artifact@v4
        if: github.event_name == 'pull_request' && matrix.record_coverage
        with:
          name: smelly-code-detector
          path: ${{ github.workspace }}/.github/workflows/smelly-code-detector.txt

      - uses: NejcZdovc/comment-pr@v2
        if: github.event_name == 'pull_request' && matrix.record_coverage
        with:
          file: smelly-code-detector.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
