name: laravel-session-release

on:
  push:
    tags:
      - laravel-session-*

defaults:
  run:
    working-directory: ./laravel-session

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Get current release semver tag
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/laravel-session-}

      - name: Publish to repository abenevaut/laravel-session
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-session.git
          BRANCH: master
          FOLDER: laravel-session
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_SESSION }}
          TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
