name: laravel-sentry-handler-test

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-sentry-handler/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'laravel-sentry-handler/**'

defaults:
  run:
    working-directory: ./laravel-sentry-handler

env:
  php_version: 8.1

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: laravel-sentry-handler-test-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          coverage: pcov

      - name: Configure Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: laravel-sentry-handler/vendor
          key: ${{ runner.os }}-node-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ env.php_version }}-

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer -V
          composer validate --strict
          composer install --optimize-autoloader --no-interaction --prefer-dist

      - name: Test
        run: vendor/bin/phpunit

      - name: Send coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml -F laravel-sentry-handler
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
