name: laravel-infrastructure-release

on:
  push:
    tags:
      - laravel-infrastructure-*

defaults:
  run:
    working-directory: ./laravel-infrastructure

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Get current release semver tag
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/laravel-infrastructure-}

      - name: Publish to repository abenevaut/laravel-infrastructure
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-infrastructure.git
          BRANCH: master
          FOLDER: laravel-infrastructure
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_INFRASTRUCTURE }}
          TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
