name: laravel-api-infrastructure-release

on:
  push:
    tags:
      - laravel-api-infrastructure-*

defaults:
  run:
    working-directory: ./laravel-api-infrastructure

jobs:

  release:
    runs-on: ubuntu-latest
    environment:
      name: laravel-api-infrastructure
      url: https://github.com/abenevaut/laravel-api-infrastructure
    concurrency:
      group: laravel-api-infrastructure-release-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get current release tag
        id: branch-name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/laravel-api-infrastructure-}" >> $GITHUB_OUTPUT

      - name: Publish to readonly repository abenevaut/laravel-api-infrastructure
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-api-infrastructure.git
          BRANCH: master
          FOLDER: laravel-api-infrastructure
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_INFRASTRUCTURE }}
          TAG: ${{ steps.branch-name.outputs.SOURCE_TAG }}
