name: laravel-session-release

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-session/**'

defaults:
  run:
    working-directory: ./laravel-session

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Publish to repository abenevaut/laravel-session
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-session.git
          BRANCH: master
          FOLDER: laravel-session
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_SESSION }}
