name: laravel-kite-release

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-kite/**'
#    tags:
#      - laravel-kite-*

defaults:
  run:
    working-directory: ./laravel-kite

env:
  php_version: 8.3

jobs:

  release:
    runs-on: ubuntu-latest
    environment:
      name: laravel-kite
      url: https://github.com/abenevaut/laravel-kite
    concurrency:
      group: laravel-kite-release
      cancel-in-progress: false
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

#      - name: Get current release tag
#        id: branch-name
#        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/laravel-kite-}

      - name: Publish to readonly repository
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-kite.git
          BRANCH: master
          FOLDER: laravel-kite
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_KITE }}
#          TAG: ${{ steps.branch-name.outputs.SOURCE_TAG }}
