name: laravel-ohdear-dev-master

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-ohdear/**'

defaults:
  run:
    working-directory: ./laravel-ohdear

jobs:

  release:
    runs-on: ubuntu-latest
    concurrency:
      group: laravel-ohdear-dev-master
      cancel-in-progress: false
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Publish to repository opensource/laravel-ohdear
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-ohdear.git
          BRANCH: master
          FOLDER: laravel-ohdear
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_OHDEAR }}
