name: laravel-one-release

on:
  push:
    tags:
      - laravel-one-*

defaults:
  run:
    working-directory: ./laravel-one

jobs:

  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php_version: [ 81 ]
    concurrency:
      group: laravel-one-release-${{ matrix.php_version }}
      cancel-in-progress: false
    container: ghcr.io/abenevaut/vapor-ci:php81
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get current release tag
        id: branch-name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/phpunit-slicer-}" >> $GITHUB_OUTPUT

#      - name: Install Chromium (required by VHS)
#        run: apk add chromium

#      - name: Install VHS
#        uses: charmbracelet/vhs-action@v2
#        with:
#          install-only: true

      - name: Install PHP extension
        run: docker-php-ext-install exif

      - name: Configure Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: laravel-one/vendor
          key: ${{ runner.os }}-node-php_${{ matrix.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ matrix.php_version }}-

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --optimize-autoloader --no-interaction --prefer-dist

#      - name: Build VHS
#        run: vhs demo.tape

      - name: Build
        run: php laravel-one app:build laravel-one --build-version=${{ steps.branch-name.outputs.SOURCE_TAG }}

      - name: Publish to readonly repository abenevaut/laravel-one
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-one.git
          BRANCH: master
          FOLDER: laravel-one
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_ONE }}
          TAG: ${{ steps.branch-name.outputs.SOURCE_TAG }}
