name: laravel-paypal-release

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-paypal/**'

defaults:
  run:
    working-directory: ./laravel-paypal

jobs:

  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/master')
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Publish to repository abenevaut/laravel-paypal
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-paypal.git
          BRANCH: master
          FOLDER: laravel-paypal
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_PAYPAL }}
