name: laravel-infrastructure-release

on:
  push:
    branches: [ master ]
    paths:
      - 'laravel-infrastructure/**'

defaults:
  run:
    working-directory: ./laravel-infrastructure

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Publish to repository abenevaut/laravel-infrastructure
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-infrastructure.git
          BRANCH: master
          FOLDER: laravel-infrastructure
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_STANDARDS }}
