name: laravel-sentry-handler-release

on:
  push:
    tags:
      - laravel-sentry-handler-*

defaults:
  run:
    working-directory: ./laravel-sentry-handler

jobs:

  release:
    runs-on: ubuntu-latest
    environment:
      name: laravel-entry-handler
      url: https://github.com/abenevaut/laravel-entry-handler
    concurrency:
      group: laravel-sentry-handler-release-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get current release semver tag
        id: branch-name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/laravel-sentry-handler-}" >> $GITHUB_OUTPUT

      - name: Publish to repository opensource/laravel-sentry-handler
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/laravel-sentry-handler.git
          BRANCH: master
          FOLDER: laravel-sentry-handler
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_LARAVEL_SENTRY_HANDLER }}
          TAG: ${{ steps.branch-name.outputs.SOURCE_TAG }}
