name: phpunit-slicer-release

on:
  push:
    tags:
      - phpunit-slicer-*

defaults:
  run:
    working-directory: ./phpunit-slicer

env:
  php_version: 8.1

jobs:

  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: phpunit-slicer-release
      cancel-in-progress: false
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get current release semver tag
        id: branch-name
        run: echo "SOURCE_TAG=${GITHUB_REF#refs/tags/phpunit-slicer-}" >> $GITHUB_OUTPUT

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}

      - name: Configure Composer cache
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: phpunit-slicer/vendor
          key: ${{ runner.os }}-node-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ env.php_version }}-

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --optimize-autoloader --no-interaction --prefer-dist

      - name: Build
        run: php phpunit-slicer app:build phpunit-slicer --build-version=${{ steps.branch-name.outputs.SOURCE_TAG }}

      - name: Publish to readonly repository abenevaut/phpunit-slicer
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/phpunit-slicer.git
          BRANCH: master
          FOLDER: phpunit-slicer
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_PHPUNIT_SLICER }}
          TAG: ${{ steps.branch-name.outputs.SOURCE_TAG }}
