name: phpunit-slicer-release

on:
  release:
    types: [ published ]
    paths:
      - 'phpunit-slicer/**'

defaults:
  run:
    working-directory: ./phpunit-slicer

env:
  php_version: 8.1

jobs:

  release:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/phpunit-slicer-')
    concurrency:
      group: phpunit-slicer-release
      cancel-in-progress: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Get current release tag
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/phpunit-slicer-}
      - name: Validate composer file
        run: composer validate --strict
      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
      - name: Configure Composer cache
        uses: actions/cache@v2
        with:
          path: ~/vendor
          key: ${{ runner.os }}-node-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ env.php_version }}-
      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install -o --no-interaction --prefer-dist
      - name: Build
        run: php phpunit-slicer app:build phpunit-slicer --build-version=${{ steps.branch_name.outputs.SOURCE_TAG }}
      - name: Publish to readonly repository
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:abenevaut/phpunit-slicer.git
          BRANCH: master
          FOLDER: phpunit-slicer
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY_PHPUNIT_SLICER }}
          TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
