name: phpunit-slicer-test

on:
  push:
    branches: [ master ]
    paths:
      - 'phpunit-slicer/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'phpunit-slicer/**'

defaults:
  run:
    working-directory: ./phpunit-slicer

env:
  php_version: 8.1

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: phpunit-slicer-test
      cancel-in-progress: true
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize PHP ${{ env.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          coverage: pcov

      - name: Configure Composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: phpunit-slicer/vendor
          key: ${{ runner.os }}-node-php_${{ env.php_version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-node-php_${{ env.php_version }}-

      - name: Composer install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer -V
          composer validate --strict
          composer install -o --no-interaction --prefer-dist

      - name: Test
        run: php phpunit-slicer test

      - name: Send coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage/clover.xml -F phpunit-slicer
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
