name: vapor-roadrunner-test

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'vapor-roadrunner/**'

defaults:
  run:
    working-directory: ./vapor-roadrunner

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: [ "linux/adm64", "linux/arm64" ]
        php_version: [ 81, 82, 83 ]
        include:
          - php_version: 81
            platform: "linux/adm64"
            build_tag: 81-amd
          - php_version: 82
            platform: "linux/arm64"
            build_tag: 82-arm
          - php_version: 82
            platform: "linux/adm64"
            build_tag: 82-amd
          - php_version: 83
            platform: "linux/arm64"
            build_tag: 83-arm
          - php_version: 83
            platform: "linux/adm64"
            build_tag: 83-amd
    concurrency:
      group: vapor-roadrunner-test-${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}-${{ matrix.php_version }}
      cancel-in-progress: true
    steps:

    - uses: actions/checkout@v4

    - uses: actions/cache@v3
      with:
        path: vapor-roadrunner/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    #- run: gem install bundler -v 2.4.22

    - run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: |
        bundle exec rubocop
        bundle exec rspec
      env:
        VAPOR_VERSION: ${{ matrix.build_tag }}
        VAPOR_PLATFORM: ${{ matrix.platform }}
