name: vapor-ci-build

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'vapor-ci/**'
      - 'docker-compose.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php_version: [ 81, 82, 83 ]
    concurrency:
      group: vapor-ci-build-${{ github.workflow }}-${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: true
    steps:

    - uses: actions/checkout@v4

    - name: Prepare environment
      run: cp .env.example .env

    - name: Build docker image
      run: TAG_VAPOR_CI=php${{ matrix.php_version }} docker-compose build vapor-ci
