name: vapor-roadrunner-test

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'vapor-roadrunner/**'

defaults:
  run:
    working-directory: ./vapor-roadrunner

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php_version: [ 81, 82, 83 ]
    concurrency:
      group: vapor-roadrunner-test-${{ github.workflow }}-${{ github.ref }}-${{ matrix.php_version }}
      cancel-in-progress: true
    steps:

    - uses: actions/checkout@v4

    - uses: actions/cache@v3
      with:
        path: vapor-roadrunner/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    #- run: gem install bundler -v 2.4.22

    - run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - run: |
        bundle exec rubocop
        bundle exec rspec
      env:
        VAPOR_VERSION: ${{ matrix.php_version }}
