name: vapor-ci-build

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'vapor-ci/**'
      - 'docker-compose.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    concurrency:
      group: vapor-ci-build-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:

    - uses: actions/checkout@v2

    - name: Prepare environment
      run: cp .env.example .env

    - name: Build docker image
      run: docker-compose build vapor-ci
