name: vapor-roadrunner-publish

on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ "linux/amd64", "linux/arm64" ]
        php_version: [ 81, 82, 83 ]
        include:
          - php_version: 81
            platform: "linux/amd64"
            build_tag: 81
          - php_version: 82
            platform: "linux/arm64"
            build_tag: 82-arm
          - php_version: 82
            platform: "linux/amd64"
            build_tag: 82
          - php_version: 83
            platform: "linux/arm64"
            build_tag: 83-arm
          - php_version: 83
            platform: "linux/amd64"
            build_tag: 83
    concurrency:
      group: vapor-roadrunner-release-${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}-${{ matrix.php_version }}
      cancel-in-progress: false
    steps:

      - uses: actions/checkout@v4

      - name: Prepare environment
        run: cp .env.example .env

      - name: Log to docker hub
        run: docker login ghcr.io --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Build "latest" docker image
#        if: ${{ matrix.latest }}
#        run: TAG_VAPOR_ROADRUNNER=latest VAPOR_VERSION=${{ matrix.build_tag }} VAPOR_PLATFORM=${{ matrix.platform }} docker-compose build vapor-roadrunner

#      - name: Publish "latest" docker image
#        if: ${{ matrix.latest }}
#        run: TAG_VAPOR_ROADRUNNER=latest docker-compose push vapor-roadrunner

#      - name: Build "release-candidate" docker image
#        if: ${{ matrix.release-candidate }}
#        run: TAG_VAPOR_ROADRUNNER=release-candidate VAPOR_VERSION=${{ matrix.build_tag }} VAPOR_PLATFORM=${{ matrix.platform }} docker-compose build vapor-roadrunner
#
#      - name: Publish "release-candidate" docker image
#        if: ${{ matrix.release-candidate }}
#        run: TAG_VAPOR_ROADRUNNER=release-candidate docker-compose push vapor-roadrunner

      - name: Build "php${{ matrix.php_version }}" docker image
        run: TAG_VAPOR_ROADRUNNER=php${{ matrix.build_tag }} VAPOR_VERSION=${{ matrix.build_tag }} VAPOR_PLATFORM=${{ matrix.platform }} docker-compose build vapor-roadrunner

      - name: Publish "php${{ matrix.php_version }}" docker image
        run: TAG_VAPOR_ROADRUNNER=php${{ matrix.build_tag }} docker-compose push vapor-roadrunner
